hosts:
    - name: R1
      ip: 192.168.1.101
      username: student
      password: Meilab123
      port: 22
      type: cisco_ios
      cmd: "show running-config"
      connection:
        - R2
        - R3
        - R4
    
    - name: R2
      ip: 192.168.1.102
      username: student
      password: Meilab123
      port: 22
      type: cisco_ios
      cmd: "show running-config"
      connection:
        - R1
      
    - name: R3
      ip: 192.168.1.103
      username: student
      password: Meilab123
      port: 22
      type: cisco_ios
      cmd: "show running-config"
      connection:
        - R1

    - name: R4
      ip: 192.168.1.104
      username: student
      password: Meilab123
      port: 22
      type: cisco_ios
      cmd: "show running-config"
      connection:
        - R1